### ISSUE TITLE
Getting already subscribed message

### ISSUE THREAD

**Issue by emmetje** [ddimitrioglo/jquery-mailchimp#1]
Hi, thanks for your plugin, how can I get a already subscribed message?

**Comment by ddimitrioglo** [comment]
You are welcome @emmetje!
Do you mean the message when you try to subscribe with the same email a few times?

**Comment by emmetje** [comment]
Yes that's exactly what I mean.

**Comment by ddimitrioglo** [comment]
@emmetje just add `onOk` & `onFail` handlers:

```javascript
$('#subscribe-form').MailChimpForm({
  url: '<some/mailchimp/url>',
  fields: '0:SOMEFIELD',
  submitSelector: '#submit-form',
  onOk: (message) => {
    console.log(message);
  },
  onFail: (message) => {
    console.log(message);
  }
});
```

and try to reproduce your use case.

Please let me know if will face some difficulties.

**Comment by emmetje** [comment]
Thx, added a div with id subscribe-result to the from and this code:
```
onFail: (message) => {
  $('#subscribe-result').html('<p>' + message + '</p>')
}
```
Works fine, thanks again!

**Comment by ddimitrioglo** [comment]
@emmetje I'm glad it helped you!
